'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, ShoppingBag, Trash2, ShieldCheck } from 'lucide-react';
import { Brand } from './chat-app';
import { ProductImage, money } from './product-card';
import type { SessionView } from '../shared/web-types';
export function CartPage() {
  const [state, setState] = useState<SessionView | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch('/api/cart').then(async r => { if (!r.ok) throw Error(); setState(await r.json()); }).catch(() => setError('Не удалось загрузить корзину. Обновите страницу.')); }, []);
  async function remove(id: number) { setBusy(true); setError(''); try { const r = await fetch('/api/cart', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'remove', id }) }); if (!r.ok) throw Error(); setState(await r.json()); } catch { setError('Не удалось удалить товар. Попробуйте снова.'); } finally { setBusy(false); } }
  const total = state?.cart.reduce((sum, item) => sum + item.quantity * item.product.price, 0) ?? 0;
  return <div className="cart-page"><header className="cart-header"><Brand /><Link href="/" className="text-button"><ArrowLeft size={16} /> К помощнику</Link></header><main className="cart-container"><span className="eyebrow">ВАШ ВЫБОР</span><h1>Демо-корзина<span className="cart-heading-count">{state?.cart.length ?? 0}</span></h1><div className="cart-notice"><ShieldCheck size={21} /><p>Это корзина прототипа. Заказ в EKT не оформляется, товары не резервируются. Остаток и цена проверены в момент добавления.</p></div>{error && <div className="error-banner" role="alert">{error}</div>}{!state && !error ? <p>Загружаем корзину…</p> : state?.cart.length ? <div className="cart-layout"><div className="cart-items">{state.cart.map(({ product: p, quantity }) => <article className="cart-item" key={p.id}><ProductImage product={p} /><div className="cart-item-content"><span className="article">Артикул {p.article}</span><h3>{p.name}</h3><a href={p.url} target="_blank" rel="noreferrer">Посмотреть на EKT <ArrowUpRight size={13} /></a><div className="cart-item-bottom"><span>{quantity} шт. × {money(p.price)}</span><strong>{money(quantity * p.price)}</strong></div></div><button className="remove-button" disabled={busy} onClick={() => void remove(p.id)} aria-label={`Удалить ${p.article}`}><Trash2 size={18} /></button></article>)}</div><aside className="cart-summary"><h2>Ваш выбор</h2><div><span>Товарных позиций</span><strong>{state.cart.length}</strong></div><div className="total"><span>Сумма</span><strong>{money(total)}</strong></div><p>Валюта в API не указана. Сумма рассчитана по ценам при добавлении и не является предложением к оплате.</p><a className="orange-button" href="https://ekt.kz" target="_blank" rel="noreferrer">Перейти на ekt.kz <ArrowUpRight size={17} /></a><span className="tiny muted">Товары на сайт автоматически не переносятся.</span></aside></div> : state && <div className="empty-cart"><span><ShoppingBag size={40} strokeWidth={1.3} /></span><h2>Здесь будет ваш выбор</h2><p>Найдите товар с помощником и подтвердите добавление.</p><Link className="orange-button" href="/">Найти товар <ArrowUpRight size={17} /></Link></div>}</main></div>;
}
