'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowUp, ArrowUpRight, Check, ChevronRight, CircleHelp, FileText, Layers3, LoaderCircle, MessageSquare, PackageCheck, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, X, Zap } from 'lucide-react';
import { ProductCard } from './product-card';
import type { ChatMessage, SessionView } from '../shared/web-types';
const quick = [
  { icon: Search, title: 'Найти товар', subtitle: 'По артикулу или названию', prompt: 'Найди товар с артикулом 200300283' },
  { icon: PackageCheck, title: 'Проверить наличие', subtitle: 'Актуальные остатки на складах', prompt: 'Проверь наличие товара с артикулом 200300283' },
  { icon: Layers3, title: 'Подобрать аналог', subtitle: 'Сравнить реальные товары', prompt: 'Подбери аналог товара с артикулом 200300283' },
  { icon: FileText, title: 'Характеристики', subtitle: 'Разобраться в технических деталях', prompt: 'Покажи характеристики товара с артикулом 200300285_' },
];
export function Brand() { return <Link className="brand" href="/"><span className="brand-icon"><Zap size={23} fill="currentColor" /></span><span>ekt<span className="brand-dot">.</span>kz</span><span className="ai-tag">AI</span></Link>; }
export function ChatApp() {
  const [state, setState] = useState<SessionView>({ messages: [], cart: [], pending: null });
  const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [ready, setReady] = useState(false);
  const [error, setError] = useState(''); const bottom = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { fetch('/api/session').then(async r => { const data = await r.json(); if (!r.ok) throw Error(data.error); setState(data); }).catch(() => setError('Не удалось загрузить сессию. Обновите страницу.')).finally(() => setReady(true)); }, []);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth' }); }, [state.messages, loading]);
  async function request(path: string, body: unknown, optimistic?: string) {
    if (loading || !ready) return;
    setLoading(true); setError('');
    if (optimistic) setState(s => ({ ...s, messages: [...s.messages, { id: crypto.randomUUID(), role: 'user', text: optimistic }] }));
    try { const response = await fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw Error(data.error || 'Не удалось получить ответ.'); setState(data); }
    catch (e) { setError(e instanceof Error ? e.message : 'Ошибка соединения. Попробуйте снова.'); }
    finally { setLoading(false); inputRef.current?.focus(); }
  }
  function send(text: string) { if (!text.trim() || loading) return; setInput(''); void request('/api/chat', { message: text.trim() }, /(?:\d[ -]?){13,19}/.test(text) ? 'Сообщение скрыто: возможно, содержит платёжные данные.' : text.trim()); }
  const count = state.cart.reduce((n, item) => n + item.quantity, 0);
  const isEmpty = state.messages.length === 0;
  return <div className="app-shell">
    <aside className="sidebar"><Brand /><div className="sidebar-caption">ЭЛЕКТРОТЕХНИКА. ПРОСТО.</div><div className="sidebar-nav"><span className="nav-label">РАБОЧЕЕ ПРОСТРАНСТВО</span><Link className="nav-item active" href="/"><MessageSquare size={18} /> AI-помощник <span className="live-dot" /></Link><Link className="nav-item" href="/cart"><ShoppingBag size={18} /> Демо-корзина {count > 0 && <span className="count">{count}</span>}</Link><a className="nav-item" href="https://ekt.kz" target="_blank" rel="noreferrer"><Layers3 size={18} /> Каталог EKT <ArrowUpRight size={14} /></a></div><div className="sidebar-guide"><div className="guide-icon"><ShieldCheck size={22} /></div><h3>Ответы на основе данных</h3><p>Товары и характеристики — из каталога EKT. Наличие проверяем перед добавлением.</p><span>Без выдуманных параметров <Check size={13} /></span></div><div className="sidebar-bottom"><span className="demo-dot" /> HackAlem AI · демо-прототип<span>Разработано для уверенного выбора</span></div></aside>
    <main className="chat-main"><header className="topbar"><div className="mobile-brand"><Brand /></div><div className="header-title"><span className="header-icon"><Sparkles size={18} /></span><div><strong>Помощник по электротехнике</strong><span><i /> Подключён к каталогу EKT</span></div></div><div className="header-right"><span className="prototype">ДЕМО</span><Link href="/cart" className="header-cart" aria-label="Открыть демо-корзину"><ShoppingBag size={19} /><span className="desktop-text">Корзина</span>{count > 0 && <b>{count}</b>}</Link></div></header>
    <div className={`conversation ${isEmpty ? 'empty' : ''}`}>
      {isEmpty ? <div className="welcome"><div className="welcome-kicker"><span /><Sparkles size={14} /> ВАШ AI-КОНСУЛЬТАНТ</div><h1>Нужная электротехника.<br /><span>Без лишних поисков.</span></h1><p className="welcome-description">Помогу найти товар, проверить наличие и разобраться<br className="desktop-text" /> в характеристиках. Просто расскажите, что вам нужно.</p><div className="quick-grid">{quick.map(({ icon: Icon, title, subtitle, prompt }) => <button key={title} disabled={!ready || loading} onClick={() => { setInput(prompt); inputRef.current?.focus(); }} className="quick-card"><span className="quick-icon"><Icon size={21} /></span><ChevronRight className="quick-arrow" size={17} /><strong>{title}</strong><span>{subtitle}</span></button>)}</div><div className="welcome-note"><ShieldCheck size={15} /> Реальные товары · Проверяемые данные · Добавление после подтверждения</div></div> : <div className="message-list"><div className="conversation-date">Ваш консультант EKT AI</div>{state.messages.map(m => <div key={m.id} className={`message-row ${m.role}`}><div className={`avatar ${m.role}`}>{m.role === 'assistant' ? <Zap size={17} fill="currentColor" /> : 'Вы'}</div><div className="message-body"><div className="message-label">{m.role === 'assistant' ? <>EKT AI <span>помощник</span></> : 'Вы'}</div><div className="bubble">{m.text}</div>{m.products && m.products.length > 0 && <div className="product-results">{m.products.map(p => <ProductCard key={p.id} product={p} disabled={loading} onAsk={send} onAdd={(id, quantity) => void request('/api/cart', { action: 'propose', id, quantity })} />)}</div>}{m.proposal && <div className="confirmation"><ShieldCheck size={20} /><div><strong>Требуется ваше подтверждение</strong><p>{m.proposal.quantity} шт. · арт. {m.proposal.product.article}</p><div className="confirmation-actions"><button className="orange-button" disabled={loading || state.pending?.token !== m.proposal.token} onClick={() => void request('/api/cart', { action: 'confirm', token: m.proposal!.token })}>{state.pending?.token === m.proposal.token ? 'Да, добавить' : 'Подтверждение закрыто'}</button>{state.pending?.token === m.proposal.token && <button className="text-button" disabled={loading} onClick={() => void request('/api/cart', { action: 'cancel' })}>Отмена</button>}</div></div></div>}{m.cartLink && <Link className="cart-link" href="/cart">Открыть демо-корзину <ArrowUpRight size={17} /></Link>}</div></div>)}{loading && <div className="message-row assistant"><div className="avatar assistant"><Zap size={17} fill="currentColor" /></div><div className="loading-bubble"><span className="thinking-dots"><i /><i /><i /></span> Проверяю данные EKT</div></div>}<div ref={bottom} /></div>}
    </div><footer className="composer-area">{error && <div className="error-banner" role="alert"><CircleHelp size={18} /><span>{error}</span><button aria-label="Закрыть ошибку" onClick={() => setError('')}><X size={15} /></button></div>}{!isEmpty && <div className="followups">{['Проверь наличие', 'Покажи характеристики', 'Подбери аналог', 'Есть сертификат?'].map(text => <button disabled={loading} key={text} onClick={() => send(text)}>{text}</button>)}</div>}<form className="composer" onSubmit={e => { e.preventDefault(); send(input); }}><span className="composer-spark"><Sparkles size={20} /></span><textarea ref={inputRef} value={input} onChange={e => setInput(e.target.value)} placeholder="Название, артикул или ваш вопрос…" aria-label="Сообщение помощнику" rows={1} maxLength={4000} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(input); } }} /><button className="send-button" type="submit" disabled={loading || !ready || !input.trim()} aria-label="Отправить сообщение">{loading ? <LoaderCircle className="spin" size={20} /> : <ArrowUp size={22} />}</button></form><div className="composer-caption"><span>AI помогает с выбором. Важные параметры уточняйте у EKT.</span><span>Не отправляйте данные карты</span></div></footer></main>
  </div>;
}
